
@startuml uc3and4
actor User
participant "MainWindow" as UI
participant "DietManager" as DM
participant "FoodDatabase" as FDB
participant "UserManager" as UM
participant "DailyLog" as DL

title Database Saving Scenarios

== Manual Database Save ==
User -> UI : Select "Save" option
activate UI

UI -> DM : save()
activate DM

par Database Saves
    DM -> FDB : save()
    activate FDB
    FDB --> DM : confirm save
    deactivate FDB
also
    DM -> UM : save()
    activate UM
    UM --> DM : confirm save
    deactivate UM
also
    DM -> DL : save()
    activate DL
    DL --> DM : confirm save
    deactivate DL
end

DM --> UI : all saves completed
UI --> User : Confirm successful saving

deactivate DM
deactivate UI

== Automatic Save on Exit ==
User -> UI : Close application
activate UI

UI -> DM : save()
activate DM

par Database Saves
    DM -> FDB : save()
    DM -> UM : save()
    DM -> DL : save()
end

DM --> UI : saves completed
UI --> User : Exit application

deactivate DM
deactivate UI

@enduml
